using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ContratCadre
{
    public partial class Form1 : Form
    {
        dbEntities dbContext;

        public Form1()
        {
            InitializeComponent();
        }

        private void contractBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            this.dbContext.SaveChanges();

            // Refresh the controls to show the values          
            // that were generated by the database. 
            this.contractDataGridView.Refresh();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            dbContext = new dbEntities();
            contractBindingSource.DataSource = dbContext.Contracts;
            this.contractDataGridView.Refresh();
        }


        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
       
            dbContext.Dispose();
        }
    }
}
