//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContratCadre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long ItemId { get; set; }
        public long ContractId { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
